---
commitizen:
  change_type_map:
    feat: Features
    fix: Bugs
  name: cz_conventional_commits
  tag_format: v$version
  version: 0.1.0
  version_files:
  - Makefile:VERSION
  - pyproject.toml:version
